Trello/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('tasks/',include('tasks.urls')),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = "tasks"

urlpatterns = [

    path('<int:id_user>',views.index,name='index'),
    path('/<int:id_user>/insertTask',views.insertTask,name='insertTask'),
    path('<int:id_user>/<int:id_task>/updateTask',views.updateTask,name="updateTask"),
    path('<int:id_task>/deleteTask',views.deleteTask,name="deleteTask")

]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path('InsertUser/',views.insertUser,name="insertUser"),
    path('loginUser',views.LoginUser,name='loginUser'),
]

tasks/models.py
from django.db import models
from users.models import User

# Create your models here.
class Task(models.Model):
    title_text = models.CharField(max_length=200)
    description_text = models.CharField(max_length=200)
    status_text = models.CharField(max_length=200,default='Pendente')
    userMaker = models.ForeignKey(User,on_delete=models.CASCADE,related_name='userMaker')
    userAssign = models.ForeignKey(User,on_delete=models.CASCADE,related_name='userAssign',null=True)

    def __str__(self):
        return 'name:'+ self.title_text+ ' Status:' + self.status_text + 'by user:'+ self.userMaker.__str__()

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name_text = models.CharField(max_length=200)
    email_text = models.CharField(max_length=200)
    password_text = models.CharField(max_length=200)

    def __str__(self):
        return 'name:'+ self.name_text + ' Email:' + self.email_text

tasks/views.py
from django.shortcuts import render,get_object_or_404,redirect
from users.models import User
from .models import Task
from django.db.models import Q

# Create your views here.
def index(req,id_user):
    user = get_object_or_404(User,pk=id_user)
    filter = 0

    if req.POST and  req.POST['filter'] != "all":
        tasks = Task.objects.filter(Q(userMaker = user)|Q(userAssign = user),Q(status_text = req.POST['filter']))
        if req.POST['filter'] == "Em andamento":
            filter = 1
        elif req.POST['filter'] == "Pendente":
            filter = 2
        else:
            filter = 3

    else:
        tasks = Task.objects.filter(Q(userMaker = user)|Q(userAssign = user))

    print(filter)
    return render(req,"tasks/index.html",{"user":user,"tasks":tasks,'filter':filter})

def insertTask(req,id_user):
    user = get_object_or_404(User,pk=id_user)
    data = req.POST
    try:
        user_assign = User.objects.get(email_text = data['Email'])
        Task(title_text=data['Title'],description_text=data['Description'],userMaker = user,userAssign = user_assign).save() 
        # não cria se não ouver user assing
    except: 
        Task(title_text=data['Title'],description_text=data['Description'],userMaker = user).save()

    return redirect("/tasks/"+str(user.id))

def updateTask(req,id_user,id_task):
    data = req.POST
    task = get_object_or_404(Task,pk=id_task)
    task.title_text = data['Title']
    task.description_text=data['Description']
    task.status_text = data['Status']
    try:
        user_assign = User.objects.get(email_text = data['Email'])
        task.userAssign = user_assign
        task.save()
    except:
        task.save()

    return redirect("/tasks/"+str(id_user))

def deleteTask(req,id_task):
    task = get_object_or_404(Task,pk=id_task)
    id_user = str(task.userMaker.id)
    task.delete()
    return redirect("/tasks/"+str(id_user))

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import User


def index(req):
    return render(req,"users/index.html")

def insertUser(req):
    data = req.POST
    User(name_text=data['Name'],email_text=data['Email'],password_text=data['Password']).save()


    return render(req,'users/index.html',{"message":"Conta Criada com sucesso!!"})

def LoginUser(req):
    data = req.POST
    try:
        login = User.objects.get(email_text = data['Email'],password_text = data['Password'])
        url = "/tasks/"+str(login.id)
        return redirect(url)
    except:
        return render(req,'users/index.html',{"message":"Email ou Senha ou incorretos"})

# Create your views here.

users/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Tarefas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <header class="shadow">
        <div class="navbar navbar-expand-lg bg-body-tertiary" style="flex-wrap: nowrap;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="https://cdn.icon-icons.com/icons2/112/PNG/512/task_manager_18854.png" alt="" height="60px">
                    Gerenciador de Tarefas
                </a>
            </div>
            <div class="container-fluid d-flex justify-content-end">
                    <a class="btn btn-outline-success" aria-current="page" data-bs-toggle="modal"  data-bs-target="#TaskInsert">Cadastrar Tarefa</a>
                    <a class="btn btn-danger" href="/" style="margin: 1%;">Logout</a>
            </div>
        </div>
    </header>
    <main>

        <section class="container d-flex justify-content-end" style="margin-top: 1%;">
                <form method="post" onchange="document.getElementById('sendButton').click()">
                    {% csrf_token %}
                    <fieldset>
                        <div class="d-flex">
                            <label for="Select" class="form-label p-2">Filtro:</label>
                            <select id="Select" name="filter" class="form-select">
                                <option value="all" {%if filter == 0 %}selected{%endif%}>Selecionar uma opção</option>
                                <option {%if filter == 1 %}selected{%endif%}>Em andamento</option>
                                <option {%if filter == 2 %}selected{%endif%}>Pendente</option>
                                <option {%if filter == 3 %}selected{%endif%}>concluída</option>
                            </select>
                        </div>
                        <input type="submit" hidden id="sendButton">
                    </fieldset>
                </form>
        </section>


        <section class="card-group container" style="margin-top: 2%;">

            {%for i in tasks%}
                <div class="container col-sm-6 col-lg-3" style="margin-top: 2%;">
                    <div class="card text-center" style="height: 100%;">
                        <div class="card-header">
                            <p class="card-text fw-bold" id="Title{{i.id}}">{{i.title_text}}</p>
                        </div>
                        <div class="card-body" style="display: flex;justify-content: space-between;flex-direction: column;">
                            <p class="card-text" id="Description{{i.id}}">{{i.description_text}}</p>

                            <p class="card-text">Status: <span id="Status{{i.id}}">{{i.status_text}}</span></p>
                            <div style="font-size: 12px;display: flex;flex-direction: row;justify-content: space-between;">
                                <p class="card-text">Criado: {{i.userMaker.name_text}}</p>
                                {%if i.userAssign%}
                                    <p class="card-text">Atribuido: <span id='Email{{i.id}}'>{{i.userAssign.email_text}}</span> </p>
                                {%endif%}
                            </div>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary" aria-current="page" data-bs-toggle="modal"  data-bs-target="#TaskUpdate" onclick="ChangeUpdateModal('{{i.id}}')">Editar</a>
                            {%if i.userMaker.id == user.id%}
                                <a href="{%url 'tasks:deleteTask' i.id %}" class="btn btn-danger">Delete</a>
                            {%endif%}
                            </div>
                    </div>
                </div>
            {%endfor%}
        </section>
    </main>

    <!-- Modals -->

    <div class="modal fade" id="TaskUpdate" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Editar Tarefa</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post"  id="UpdateForm" action=""> 
                        {% csrf_token %}
                        <fieldset>
                            <div class="mb-3">
                                <label for="task_title" class="form-label">Titulo:</label>
                                <input type="text" class="form-control"  name="Title" id="UpdateTitle">
                            </div>
                            <div class="mb-3">
                                <label for="Description" class="form-label">Descrição:</label>
                                <input type="text" class="form-control"  name="Description"  maxlength="100" id="UpdateDescription">
                            </div>
                            <div class="mb-3">
                                <label for="EmailAssing" class="form-label">Email da pessoa Atribuida:</label>
                                <input type="text" class="form-control"  name="Email"  maxlength="100" placeholder="Preencher apenas se houver que atribuir a outro usuario" id="UpdateEmail">
                            </div>
                            <div class="mb-3">
                                <select id="Select" required name="Status" class="form-select">
                                    <option value="" hidden selected>Selecionar uma opção</option>
                                    <option>Pendente</option>
                                    <option>Em andamento</option>
                                    <option>concluída</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary fw-bold text-uppercase">Editar Tarefa</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="TaskInsert" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Criar Tarefa</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post"  action="{%url 'tasks:insertTask' user.id %}"> 
                        {% csrf_token %}
                        <fieldset>
                            <div class="mb-3">
                                <label for="task_title" class="form-label">Titulo:</label>
                                <input type="text" class="form-control"  name="Title">
                            </div>
                            <div class="mb-3">
                                <label for="Description" class="form-label">Descrição:</label>
                                <input type="text" class="form-control"  name="Description"  maxlength="100">
                            </div>
                            <div class="mb-3">
                                <label for="EmailAssing" class="form-label">Email da pessoa Atribuida:</label>
                                <input type="text" class="form-control"  name="Email"  maxlength="100" placeholder="Preencher apenas se houver que atribuir a outro usuario">
                            </div>
                            <button type="submit" class="btn btn-primary fw-bold text-uppercase">Criar Tarefa</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
    function ChangeUpdateModal(id){
        title = document.getElementById(`Title${id}`).innerHTML;
        description = document.getElementById(`Description${id}`).innerHTML;
        try{
            email = document.getElementById(`Email${id}`).innerHTML;
        }catch{
            email = null
        }
        document.getElementById('UpdateTitle').value = title;
        document.getElementById('UpdateEmail').value = email;
        document.getElementById('UpdateDescription').value = description;
        document.getElementById('UpdateForm').action = `{{user.id}}/${id}/updateTask`
    }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <main>
        <div class="container col-sm-8 col-md-4 border" style="padding: 1%; margin-top: 1%;border-radius: 30px;">
            <div>
                <p class="fw-bold text-center fs-4">Login</p>
            </div>
            <form method="post" action="{%url 'users:loginUser'%}">
                {% csrf_token %}
                <fieldset>
                    <div class="mb-3">
                        <label for="ClassRoomName" class="form-label">Email</label>
                        <input type="text" class="form-control" name="Email">
                    </div>
                    <div class="mb-3">
                        <label for="ClassRoomCapacity" class="form-label">Senha</label>
                        <input type="password" class="form-control" name="Password">
                        <a href="#" data-bs-toggle="modal"  data-bs-target="#UserInsert" >Criar conta</a>
                        {%if message %}<p><strong>{{ message }}</strong></p>{% endif %}
                    </div>
                      <button type="submit" class="btn btn-primary fw-bold text-uppercase">Entrar</button>
                </fieldset>
            </form>
        </div>
    </main>



        <!-- Modals -->
        <div class="modal fade" id="UserInsert" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Criar conta</h2>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post"  action="{%url 'users:insertUser'%}"> 
                            {% csrf_token %}
                            <fieldset>
                                <div class="mb-3">
                                    <label for="login_name" class="form-label">name:</label>
                                    <input type="text" class="form-control"  name="Name">
                                </div>
                                <div class="mb-3">
                                    <label for="Email" class="form-label">Email:</label>
                                    <input type="text" class="form-control"  name="Email">
                                </div>
                                <div class="mb-3">
                                    <label for="Password" class="form-label">Senha:</label>
                                    <input type="password" class="form-control"  name="Password">
                                </div>
                                <button type="submit" class="btn btn-primary fw-bold text-uppercase">Criar conta</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>